 
/* THIS FILE IS AUTOGENERATED DO NOT EDIT
*
* This file is autogenerated from HResult Orm.csv.
* If you want to add a new hresult code
* do so in the CSV file then rebuild.
*/

using System.CodeDom.Compiler;

namespace OsamesMicroOrm
{
    /// <summary>
	/// Auto generated date: 02/04/2015 13:12:03
	/// </summary>
	[GeneratedCode("HResultToEnumGenerator", "1.0")]
    public enum HResultEnum
    {
        // ReSharper disable InconsistentNaming
        E_BEGINTRANSACTIONFAILED,
	                    
        E_COMMITTRANSACTIONFAILED,
	                    
        E_ROLLBACKTRANSACTIONFAILED,
	                    
        E_EXECUTEREADERFAIL,
	                    
        E_CREATEDATAADAPTERFAILED,
	                    
        E_COLUMNDOESNOTEXIST,
	                    
        E_NOROWUPDATED,
	                    
        E_LASTINSERTIDNOTNUMBER,
	                    
        E_TYPENOTDEFINEDBMAPPINGATTRIBUTE,
	                    
        E_TYPEDEFINESDBMAPPINGATTRIBUTEMOREONETIME,
	                    
        E_TYPEDEFINESEMPTYDBMAPPINGATTRIBUTE,
	                    
        E_XMLVALIDATIONERRORS,
	                    
        E_NAMESPACESSCHEMASCOUNTMISMATCH,
	                    
        E_NONAMESPACEINSCHEMA,
	                    
        E_NULLVALUE,
	                    
        E_NORULESFORGIVENPARAMETER,
	                    
        E_XMLNAMEATTRIBUTEMORETHANONETIME,
	                    
        E_FILL_TEMPLATESDICTIONARY_ERROR,
	                    
        E_NOACTIVECONNECTIONDEFINED,
	                    
        E_NOACTIVECONNECTIONFOUND,
	                    
        E_PROVIDERCONFIGMISSING,
	                    
        E_LOADCONFIGURATION,
	                    
        E_NOPROVIDERNAMEFORCONNECTIONNAME,
	                    
        E_PROVIDERNOTINSTALLED,
	                    
        E_NOCONNEXIONSTRINGDEFINED,
	                    
        E_NOMAPPINGKEYANDCOLUMN,
	                    
        E_NOMAPPINGKEY,
	                    
        E_CONFIGFILENOTFOUND,
	                    
        E_FILL_MAPPINGDICTIONARY_ERROR,
	                    
        E_NOMAPPINGKEYANDPROPERTY,
	                    
        // ReSharper disable InconsistentNaming
    }
} 

