 
/* THIS FILE IS AUTOGENERATED DO NOT EDIT
*
* This file is autogenerated from HResult Orm.csv.
* If you want to add a new hresult code
* do so in the CSV file then rebuild.
*/

using System.CodeDom.Compiler;

namespace OsamesMicroOrm
{
    /// <summary>
	/// Auto generated date: 12/29/2014 13:32:55
	/// </summary>
	[GeneratedCode("HResultToEnumGenerator", "1.0")]
    public enum HResultEnum
    {
        E_Begintransactionfail,
	
        E_Committransactionfailed,
	
        E_Rollbacktransactionfailed,
	
        E_Executereaderfail,
	
        E_Createdataadapterfailed,
	
        E_Columndoesnotexist,
	
        E_Norowupdated,
	
        E_Typenotdefinedbmappingattribute,
	
        E_Typedefinesdbmappingattributemoreonetime,
	
        E_Typedefinesemptydbmappingattribute,
	
        E_Xmlvalidationerrors,
	
        E_Namespacesschemascountmismatch,
	
        E_Nonamespaceinschema,
	
        E_Nullvalue,
	
        E_Norulesforgivenparameter,
	
        E_Xmlnameattributemorethanonetime,
	
        E_Filltemplatesdictionnaryerror,
	
        E_Noactiveconnectiondefined,
	
        E_Noactiveconnectionfound,
	
        E_Noactiveconnectionprovidername,
	
        E_Providermissing,
	
        E_Providernotmatch,
	
        E_Loadconfiguration,
	
        E_Activeconnectionnotfoundinactivecostring,
	
        E_Noprovidernameforconnectionname,
	
        E_Providernotinstalled,
	
        E_Noconnexionstringdefined,
	
        E_Nomappingkeyandcolumn,
	
        E_Nomappingkey,
	
        E_Templateanalysiserror,
	
        E_Nomappingkeyandproperty,
	
    }
} 

