 
/* THIS FILE IS AUTOGENERATED DO NOT EDIT
*
* This file is autogenerated from HResult Orm.csv.
* If you want to add a new hresult code
* do so in the CSV file then rebuild.
*/

using System.CodeDom.Compiler;

namespace OsamesMicroOrm
{
	/// <summary>
	/// Auto generated date: 02/25/2015 10:46:00
	/// </summary>
	[GeneratedCode("HResultToEnumGenerator", "1.0")]
	public enum HResultEnum
	{
		// ReSharper disable InconsistentNaming
		/// <summary>
		/// DbManager, CreateConnection: Connection could not be created! Look at detailed log for details
		/// </summary>
		E_CREATECONNECTIONFAILED,
	                    
		/// <summary>
		/// Transaction couldn't be started. See log file for details
		/// </summary>
		E_BEGINTRANSACTIONFAILED,
	                    
		/// <summary>
		/// Transaction couldn't be commited See log file for details
		/// </summary>
		E_COMMITTRANSACTIONFAILED,
	                    
		/// <summary>
		/// Transaction couldn't be rolled back. See log file for details
		/// </summary>
		E_ROLLBACKTRANSACTIONFAILED,
	                    
		/// <summary>
		/// Error during execution of an SQL query (ExecuteReader). See log file for details.
		/// </summary>
		E_EXECUTEREADERFAILED,
	                    
		/// <summary>
		/// DbHelper, DataAdapter: data adapter could not be created. See log file for details
		/// </summary>
		E_CREATEDATAADAPTERFAILED,
	                    
		/// <summary>
		/// Column doesn't exist in sql data reader, See log file for details
		/// </summary>
		E_COLUMNDOESNOTEXIST,
	                    
		/// <summary>
		/// Query didn't update any row
		/// </summary>
		E_NOROWUPDATED,
	                    
		/// <summary>
		/// Error during execution of an SQL query (ExecuteScalar). See log file for details.
		/// </summary>
		E_EXECUTESCALARFAILED,
	                    
		/// <summary>
		/// Error during execution of an SQL query (ExecuteNonQuery). See log file for details.
		/// </summary>
		E_EXECUTENONQUERYFAILED,
	                    
		/// <summary>
		/// Error during execution of an SQL query (Fill DataSet). See log file for details.
		/// </summary>
		E_FILLDATASETFAILED,
	                    
		/// <summary>
		/// Returned last insert ID value could not be parsed to Long number
		/// </summary>
		E_LASTINSERTIDNOTNUMBER,
	                    
		/// <summary>
		/// [XML] This C# class doesn't define DatabaseMapping attribute (at class level)
		/// </summary>
		E_TYPENOTDEFINEDBMAPPINGATTRIBUTE,
	                    
		/// <summary>
		/// [XML] This C# class defines DatabaseMapping attribute more than once (at class level)
		/// </summary>
		E_TYPEDEFINESDBMAPPINGATTRIBUTEMOREONETIME,
	                    
		/// <summary>
		/// [XML] This C# class defines an empty DatabaseMapping attribute (at class level)
		/// </summary>
		E_TYPEDEFINESEMPTYDBMAPPINGATTRIBUTE,
	                    
		/// <summary>
		/// [XML] XML validation errors
		/// </summary>
		E_XMLVALIDATIONERRORS,
	                    
		/// <summary>
		/// [XML] Not same number of namespaces and schemas given
		/// </summary>
		E_NAMESPACESSCHEMASCOUNTMISMATCH,
	                    
		/// <summary>
		/// [XML] Schema given but no namespaces
		/// </summary>
		E_NONAMESPACEINSCHEMA,
	                    
		/// <summary>
		/// [PARAMETER] Value cannot be null
		/// </summary>
		E_NULLVALUE,
	                    
		/// <summary>
		/// [PARAMETER] Placeholder value isn't syntactically correct according to our parsing rules. See log file for details
		/// </summary>
		E_INCORRECTPLACEHOLDERVALUE,
	                    
		/// <summary>
		/// [XML] Invalid XML, ""name"" attribute defines more than once the same value (template name in templates file)
		/// </summary>
		E_XMLNAMEATTRIBUTEMORETHANONCE,
	                    
		/// <summary>
		/// [CONF] No active connection name defined in appSettings ('activeDbConnection')
		/// </summary>
		E_NOACTIVECONNECTIONDEFINED,
	                    
		/// <summary>
		/// [CONF] Active connection not found in available connection strings
		/// </summary>
		E_NOACTIVECONNECTIONFOUND,
	                    
		/// <summary>
		/// [CONF] Provider configuration missing in orm:ProviderSpecific section of XML templates file
		/// </summary>
		E_PROVIDERCONFIGMISSING,
	                    
		/// <summary>
		/// [CONF] No provider name defined in connection strings configuration for active connection
		/// </summary>
		E_NOPROVIDERNAMEFORCONNECTIONNAME,
	                    
		/// <summary>
		/// [CONF] Provider defined is not installed
		/// </summary>
		E_PROVIDERNOTINSTALLED,
	                    
		/// <summary>
		/// [CONF] No connection string value defined in connection strings configuration for active connection
		/// </summary>
		E_NOCONNEXIONSTRINGDEFINED,
	                    
		/// <summary>
		/// [CONF] No match in mapping file for table name and column values
		/// </summary>
		E_NOMAPPINGKEYANDCOLUMN,
	                    
		/// <summary>
		/// [CONF] No match in mapping file for table name
		/// </summary>
		E_NOMAPPINGKEY,
	                    
		/// <summary>
		/// [CONF] Configuration file not found
		/// </summary>
		E_CONFIGFILENOTFOUND,
	                    
		/// <summary>
		/// [CONF] No match in mapping file for table name and property values
		/// </summary>
		E_NOMAPPINGKEYANDPROPERTY,
	                    
		/// <summary>
		/// [CONF] No connection string has been set to DbManager before using it
		/// </summary>
		E_DBMANAGERNOCONNECTIONSTRINGSET,
	                    
		/// <summary>
		/// [CONF] No SQL text for select last inserted ID has been set to DbManager before executing an insert command
		/// </summary>
		E_DBMANAGERNOSELECTLASTINSERTIDCOMMANDSET,
	                    
		/// <summary>
		/// [CONF] No provider name has been set to DbManager before using it.
		/// </summary>
		E_DBMANAGERNOPROVIDERNAME,
	                    
		/// <summary>
		/// [PARAMETER] There are less values provided than placeholders to replace for the current template string to process. See log file for details.
		/// </summary>
		E_PLACEHOLDERSVALUESCOUNTMISMATCH,
	                    
		/// <summary>
		/// [CONF] No SQL template by this name
		/// </summary>
		E_NOTEMPLATE,
	                    
		/// <summary>
		/// [PARAMETER] There are less values provided than meta names to format ADO.NET parameters. See log file for details.
		/// </summary>
		E_METANAMESVALUESCOUNTMISMATCH,
	                    
		/// <summary>
		/// [PARAMETER] ADO.NET command could not be created.
		/// </summary>
		E_ADOCOMMANDNOTCREATED,
	                    
		/// <summary>
		/// [PARAMETER] Connection cannot be null.
		/// </summary>
		E_NULLCONNECTION,
	                    
		// ReSharper restore InconsistentNaming
	}
} 

