 
/* THIS FILE IS AUTOGENERATED DO NOT EDIT
*
* This file is autogenerated from Coordinates.csv.
* If you want to add a new user interface coordinate
* do so in the CSV file then rebuild.
*/

using System.CodeDom.Compiler;

namespace OsamesMicroOrm
{
    /// <summary>
	/// Auto generated date: 12/29/2014 11:21:56
	/// </summary>
	[GeneratedCode("HResultToEnumGenerator", "1.0")]
    public enum HResultEnum
    {
        EBegintransactionfail,
	
        ECommittransactionfailed,
	
        ERollbacktransactionfailed,
	
        EExecutereaderfail,
	
        ECreatedataadapterfailed,
	
        EColumndoesnotexist,
	
        ENorowupdated,
	
        ETypenotdefinedbmappingattribute,
	
        ETypedefinesdbmappingattributemoreonetime,
	
        ETypedefinesemptydbmappingattribute,
	
        EXmlvalidationerrors,
	
        ENamespacesschemascountmismatch,
	
        ENonamespaceinschema,
	
        ENullvalue,
	
        ENorulesforgivenparameter,
	
        EXmlnameattributemorethanonetime,
	
        EFilltemplatesdictionnaryerror,
	
        ENoactiveconnectiondefined,
	
        ENoactiveconnectionfound,
	
        ENoactiveconnectionprovidername,
	
        EProvidermissing,
	
        EProvidernotmatch,
	
        ELoadconfiguration,
	
        EActiveconnectionnotfoundinactivecostring,
	
        ENoprovidernameforconnectionname,
	
        EProvidernotinstalled,
	
        ENoconnexionstringdefined,
	
        ENomappingkeyandcolumn,
	
        ENomappingkey,
	
        ETemplateanalysiserror,
	
        ENomappingkeyandproperty,
	
    }
} 

